pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
                dir("/var/lib/jenkins/workspace/frontend") {
                    script {
                        // Build the .NET project
                        sh 'dotnet publish -c Release -o out'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                //
            }
        }
        stage('Deploy') {
            steps {
                //
            }
        }
    }
}