pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Change to a specific directory for the following steps
                    dir('/var/lib/jenkins/workspace/frontend') {
                        // Steps to execute inside the specified directory
                        // For example, checkout SCM, build, test, etc.
                        checkout scm
                        sh 'mvn clean install'
                    }
                }
            }
        }

        // Add more stages as needed
    }
}
