pipeline {
    agent any
    stages {
        stage("checkout")
        {
            steps 
            {
                // Get some code from a GitHub repository

            }
        
        }
        stage("Build") {
            steps {
                dir ("/var/lib/jenkins/workspace/frontend")
                    script {
                        // Build the .NET project
                        sh 'dotnet publish -c Release -o out'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh 'make test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'make publish'
            }
        }
    }
}